version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  config-service:
#    environment:
#      CONFIG_SERVICE_PASSWORD: password
    build: config-service
#    image: webscholar/config-service
    ports:
      - 8888:8888
#    restart: always
  registry:
#    environment:
#      CONFIG_SERVICE_PASSWORD: password
    build: registry
#    image: webscholar/registry
#    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 8765:8765

  account-service:
#    environment:
#      CONFIG_SERVICE_PASSWORD: password
    build: account-service
#    image: webscholar/account-service
#    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 6001:6001