# ${} Are system env variables. Set them on your machine.
version: '2.1'
services:
  account-service:
    build: account-service
    image: webscholar/account-service
    ports:
      - 6000:6000
  db-service:
    #tried latest but it keeps crashing and restarting
    #https://github.com/docker-library/mysql/issues/665 seems relevant
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: webscholar-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3308:3306
    expose:
      - 3306
    volumes:
    - db:/var/lib/mysql
volumes:
  db:
