version: '2.1'
services:
  #Message broker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    networks:
      - front-end
      - back-end
  #Spring config-service micro-service container settings
  config-service:
#    environment:
#      CONFIG_SERVICE_PASSWORD: password
    build: config-service
#    image: webscholar/config-service
    ports:
      - 8888:8888
    networks:
      - front-end
      - back-end
#    restart: always
  registry:
#    environment:
#      CONFIG_SERVICE_PASSWORD: password
    build: registry
#    image: webscholar/registry
#    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 8765:8765
    networks:
      - front-end
      - back-end

  #Spring account-service micro-service container settings
  account-service:
#    environment:
#      CONFIG_SERVICE_PASSWORD: password
    build: account-service
#    image: webscholar/account-service
#    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 6001:6001
    expose:
      - 6001
    networks:
      - front-end
      - back-end
  #MySql container settings
  account-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: webscholar-db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_TCP_PORT: 6002
#    environment:
#      DATABASE_HOST: account-db
#      DATABASE_USER: root
#      DATABASE_PASSWORD: password
#      DATABASE_NAME: webscholar-db
#      DATABASE_PORT: 6602
    ports:
      - 6002:6002
    expose:
      - 6002
    #Data persistence for mysql database files
    volumes:
      - ./account-db:/var/lib/mysql

    networks:
      - front-end
      - back-end

#  frontend:
#    build: frontend
#    ports:
#      - 4200:4200
#    expose:
#     - 4200
#   networks:
#     - front-end

  scholarship-service:

    build: scholarship-service
    depends_on:
      config-service:
        condition: service_healthy

    ports:
      - 6003:6003
    expose:
      - 6003

    networks:
      - front-end
      - back-end

  account-scholarship-service:

    build: account-scholarship-service
    depends_on:
      config-service:
        condition: service_healthy

    ports:
      - 6004:6004
    expose:
      - 6004

    networks:
      - front-end
      - back-end


networks:
  front-end:
  back-end:
   #Old MySql container settings
#  db-service:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_DATABASE: webscholar-db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: password
#    ports:
#      - 3306:3306
#    expose:
#      - 3306
#    volumes:
#      - db:/var/lib/mysql
#volumes:
#  db: