package edu.weber.auth.model;

import java.io.Serializable;
import java.util.Set;
import java.io.Serial;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * Represents a Permission Entity and a set of roles that have said permission.
 * Many-to-Many relationship with Role entity
 */
@Entity
@Table(name="permission")
public class Permission implements  Serializable{

	// Unique identifier for serializable classes.
	@Serial
	private static final long serialVersionUID = 8087275050725156377L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="permission_id")
	private int permissionId; // Generated by the database
	
	@Column(name="permission_name")
	private String permissionName;
	
	@JsonIgnore
	@ManyToMany(mappedBy = "permissions", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	private Set<Role> roles;

	public Permission() {
		super();
	}

	public Permission(String permissionName) {
		super();
		if (permissionName == null || permissionName.trim().isEmpty()) {
			throw new IllegalArgumentException("Permission name cannot be empty");
		}
		this.permissionName = permissionName;
	}

	// All the methods below implement CRUD functionality.

	public int getPermissionId() {
		return permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	public String getPermissionName() {
		return permissionName;
	}

	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	public Set<Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	
}
