#TODO:: refactor this into the (future) config module?, use ssl when we set that up?

spring:
  datasource:
    url: jdbc:mysql://db-service:3306/webscholar-db?useSSL=false
    username: ${USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
